import { useState } from 'react';
import Header from '@/components/header';
import Head from 'next/head';

function Music() {
  const [audio, setAudio] = useState(null);
    const [isPaused, setIsPaused] = useState(true);
  const play = () => {
    if (!audio) {
      const newAudio = new Audio('/calming.mp3');
      setAudio(newAudio);
      newAudio.play();
      setIsPaused(false);
      console.log(isPaused);
    } else {
      audio.play();
      setIsPaused(false);
    }
  };

  const stop = () => {
    if (audio) {

      audio.pause();
      setIsPaused(true);

    }
  };

  return (
    <><Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head><div className='h-screen finisher-header'

          style={{
              backgroundColor: "#0cbaba",
              backgroundImage: "linear-gradient(315deg, #0cbaba 0%, #380036 74%)"
          }}
      >
              <Header />
              <div className=' flex my-72  justify-center items-center'>
                  {/* <button onClick={play} className = "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Play</button>

<button onClick={stop} className = "ml-5 text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Stop</button> */}

                  {isPaused ? (
                      <button className="" onClick={play}> <div className='w-40  '

                      >
                          <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
                              <path fill="#FF0066" d="M65.9,-24.3C71.6,-4,52.8,21.4,32.4,33.7C12,45.9,-10.1,45,-27.6,33.4C-45.2,21.7,-58.3,-0.8,-53,-20.6C-47.6,-40.5,-23.8,-57.8,3.2,-58.8C30.1,-59.8,60.2,-44.6,65.9,-24.3Z" transform="translate(100 100)" />
                          </svg>
                      </div></button>
                  ) : (
                      <button className="" onClick={stop}> <div className='w-40  '

                      >
                          <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
                              <path fill="#8c92ac" d="M65.9,-24.3C71.6,-4,52.8,21.4,32.4,33.7C12,45.9,-10.1,45,-27.6,33.4C-45.2,21.7,-58.3,-0.8,-53,-20.6C-47.6,-40.5,-23.8,-57.8,3.2,-58.8C30.1,-59.8,60.2,-44.6,65.9,-24.3Z" transform="translate(100 100)" />
                          </svg>
                      </div></button>
                  )}
              </div></div></>
  );
}

export default Music;